### ISSUE TITLE
Change the direction of chromosome in dot plot? 

### ISSUE THREAD

**Issue by YingChen94** [yhw320/PanSyn#1]
Hello, would it be possible to modify the direction of the chromosome (red circle) to be the same linear direction as other chromosomes in dot plot? 
<img width="626" alt="Screenshot 2024-05-13 at 11 20 29 PM" src="https://github.com/yhw320/PanSyn/assets/46506947/8d0eb2fc-22ba-4b5d-939c-0041d8bd3d4b">

**Comment by yhw320** [comment]
Hi, I get what you're saying.
In fact, the two directions depicted in the result figure indicate the forward and reverse orientations when genes undergo microsynteny pairing, which is meaningful. The last column (-1 or 1) in the result file (*.collinearity) dictates the orientation in the result figure.

If you want to modify the direction, you can replace the positions of genes in the simplified GFF file corresponding to chr1 with the positions in the opposite strand, and then try running it again. I feel like this should give you the result figure you're aiming for..

**Comment by YingChen94** [comment]
Hi Hongwei, thank you for your fast reply! Indeed, after modifying the positions of genes in the simplified GFF file (i.e. reversing the orientation of the chromosome), I got what I want. I attach my codes here in case anyone else wish to do the same thing:
```
awk -v OFS='\t' 'BEGIN{start=""; end=""; strand="";} 
    {if ($1=="chr1"){
        start=624143582-$4 # 624143582 is chromosome length
        end=624143582-$3 # # 624143582 is chromosome length
        if ($5=="+"){strand="-"}
        else if ($5=="-"){strand="+"}
        print $1,$2,start,end,strand
        } else {print $1,$2,$3,$4,$5}
    }' xxxx_simplified_chr_original.gff > xxxx_simplified_chr.gff
```

<img width="819" alt="Screenshot 2024-05-14 at 11 11 39 AM" src="https://github.com/yhw320/PanSyn/assets/46506947/76afb6f8-87ce-4be5-9db1-e757fd843301">

**Comment by yhw320** [comment]
Thank you for sharing your codes!
