### ISSUE TITLE
conda install error

### ISSUE THREAD

**Issue by lijunyuan** [yhw320/PanSyn#10]
Dears,
I installed pansyn as the instructions of the protocol in the Nature Protocol with conda 24.11.1. To check the channels, I used the
conda config --show channels
channels:
  - conda-forge
  - bioconda
  - r
  - dnachun
  - seqera
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  Then I followed the instructions:
$ conda create --name pansyn
$ conda activate pansyn
$ conda install -c micromacro pansyn -y
However, an error occurred:
Solving environment: failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - nothing provides kent-tools 438.* needed by pansyn-1.0.12-py311_0

Could not solve for environment specs
The following package could not be installed
└─ pansyn is not installable because it requires
   └─ kent-tools 438.* , which does not exist (perhaps a missing channel).

I also tried the mamba method, the same error also existed. 
Then I tried to install the kent-tools with the command "conda install conda-forge::kent", and installed pansyn with command:
$ conda install -c micromacro pansyn -y,
the same error still appeared with kent-tools 438.*  not present. Could you please check what is the problem.
Thanks a lot!
Junyuan Li

**Comment by yhw320** [comment]
Thank you for using pansyn. 

When we packaged the dependencies for pansyn, we utilized version 438 of kent-tools. However, version 438 of kent-tools was removed from the conda repository by its developers two months ago. I attempted to contact the author of kent-tools to restore version 438, but it appears to be challenging. 

Given the numerous dependencies in pansyn, it will take some time to repackage and upload a new version. In the meantime, I recommend using the Docker version for your conda installation to avoid any dependency installation issues. We will update the conda installation process

**Comment by lijunyuan** [comment]
Could you please upload a singularity file to the github, I have tried to pull it with "singularity pull docker://micromacro/pansyn:latest", but there are errors"
FATAL:   While making image from oci registry: error fetching image to cache: failed to get checksum for docker://micromacro/pansyn:latest: pinging container registry registry-1.docker.io: Get "https://registry-1.docker.io/v2/": dial tcp 104.23.125.189:443: i/o timeout
". It will be more convenient to download sif file, I think.

**Comment by yhw320** [comment]
Maybe you can try it with these commands:
$ docker pull micromacro/pansyn:latest
$ docker run -it -v <your_host_path>:<your_container_path> micromacro/pansyn:latest /bin/bash
$ source activate Pansyn
$ source /opt/conda/envs/Pansyn/cns_solve_1.3/cns_solve_env.sh

**Comment by yhw320** [comment]
Hi, 
we have updated the version of PanSyn available in the Conda repository to 2.0.8. This update resolves the previous issue that prevented the installation of kent-tools software from causing errors.If needed, you can now opt to install it using conda.

**Comment by lijunyuan** [comment]
Install finished, thanks!
