### ISSUE TITLE
The All_species_microsyn_genes.links file is missing based on the results of data analysis using a script Microsyn_cluster

### ISSUE THREAD

**Issue by maxnest** [yhw320/PanSyn#2]
Dear colleagues, 
Thanks for the extremely important and useful pipeline! Unfortunately, I have some issues with the Step 4 in microsynteny analysis (“Visualization and comparison of conserved gene clusters”). Step VI states the following: “Select a gene cluster of interest from the ‘All_species_microsyn_genes.links’ file generated from Step 4A(iv) and save it as a new file named ‘A_single.cluster’.” However, I cannot find the file 'All_species_microsyn_genes.links' in the Microsyn_cluster results on both my own and test data. Could you please tell me, is there a typo in the instructions and do you mean the file created in step 2(iii), or am I missing something? I would be grateful for any help!
Thanks a lot, 
Maksim

**Comment by yhw320** [comment]
Dear Maksim,
Thank you for your recognition of PanSyn, and I apologize for any inconvenience caused.
Initially, I named the results file generated from Step 4A(iv) as 'All_species_microsyn_genes.links', but this led to confusion with the output file from step 2(iii). Therefore, we have updated the name of the results file.
You can now select a gene cluster of interest from the 'final_conserved.clusters' file generated in Step 4A(iv). We will further update instructions on our GitHub repository as we continue to upgrade PanSyn.
Please let me know if you encounter any further issues or if you need any further assistance.
Best regards,
Hongwei

**Comment by maxnest** [comment]
Dear Hongwei, 
Thank you very much for your answer and help! 
Now I have found the necessary files and will continue working with them!
Best regards,
Maksim
