### ISSUE TITLE
Difference between red and blue points in dot plot?

### ISSUE THREAD

**Issue by YingChen94** [yhw320/PanSyn#3]
Hello, there are two colors (red and blue) in the example dot plot in step 2B (attached). What's the difference between those two colors? Thanks!

<img width="367" alt="Screenshot 2024-05-15 at 12 02 27 AM" src="https://github.com/yhw320/PanSyn/assets/46506947/30dd9316-dd4c-40d4-8225-1a387e87d631">

**Comment by yhw320** [comment]
Hi,
The program sorted homologous genes into red and blue dots according to their homology.
If we set "multiple" to "1" (e.g. mutiple = 1) in the "wgdi-dotplot.conf" file, the red in the dot plot  is the homologous genes with the highest score.

**Comment by YingChen94** [comment]
Thank you for the explanation!
