### ISSUE TITLE
Missing Step1 folder 

### ISSUE THREAD

**Issue by GabrieleRigano99** [yhw320/PanSyn#5]
Hi! Thanks for developing this tool. It seems pretty useful!
I am struggling to find Step1 folder in the demo dataset, could you help me out?
Thanks!

**Comment by yhw320** [comment]
Thank you for using PanSyn!
In the first step we explained how to install PanSyn, so there is no data to provide in the demo dataset. The actual computational procedure commences with the second step.

**Comment by GabrieleRigano99** [comment]
Oh I get it now! thanks!
