### ISSUE TITLE
The file 'genes.links' is empty after running Change_link_color

### ISSUE THREAD

**Issue by HyCipher** [yhw320/PanSyn#6]
Hi!
I ran this program on the drosophila dataset. But once when I ran code `Change_link_color -i <All_species_microsyn_genes.links> -c <chr_link_color.txt> - o outputDir_S1`. It only creates an empty file with the name <genes.links>, there is no content inside like in exemplar.
How can I solve this problem?
[All_species_microsyn_genes.links.zip](https://github.com/user-attachments/files/16517254/All_species_microsyn_genes.links.zip)
![Screenshot 2024-08-07 at 10 24 03](https://github.com/user-attachments/assets/c8ff331f-9d0c-408d-b6fa-853731c1e6b3)

**Comment by yhw320** [comment]
Hello there,

I ran the command using the "All_species_microsyn_genes.links" file you provided, and successfully generated the "genes.links" file. Here are the commands I used:

`conda activate pansyn`
`cd try`
`Change_link_color -i All_species_microsyn_genes.links -c chr_link_color.txt -o outputDir_S1`

I have placed both input files (All_species_microsyn_genes.links and chr_link_color.txt), as well as the output file (genes.links), here. Feel free to try running it again. If you encounter any further issues, please don't hesitate to ask me.
[try.zip](https://github.com/user-attachments/files/16517353/try.zip)

**Comment by HyCipher** [comment]
Thanks, it solves. In creating <chr_link_color.txt>, the entered tab characters were read as spaces in the program. I think it would be better to use the tsv file format rather than the txt file format since it looks very similar between tab and space in the txt file.

**Comment by yhw320** [comment]
Great to hear it solved the issue! Using the TSV  file format sounds like a good idea. Thanks for the suggestion!
