### ISSUE TITLE
No "All_species_microsyn_genes.links" was generated from Step 4A

### ISSUE THREAD

**Issue by Neo-xbx-00** [yhw320/PanSyn#8]
Hello,
Recently, I conduct Microsynteny analyses based on your protocal step by step, based on your protocal. You mentioned a file "‘All_species_microsyn_genes.links" file generated from Step 4A(iv), which involves gene clusters of interest. But I can not find it. From which step was it generated?

**Comment by yhw320** [comment]
Hi,

I'm sorry to have caused you trouble.
Initially, I named the results file generated from Step 4A(iv) as 'All_species_microsyn_genes.links', but this led to confusion with the output file from step 2(iii). Therefore, we have updated the name of the results file.
You can now select a gene cluster of interest from the 'final_conserved.clusters' file generated in Step 4A(iv). We will further update instructions on our GitHub repository as we continue to upgrade PanSyn.
Please let me know if you encounter any further issues or if you need any further assistance.

Hongwei

**Comment by Neo-xbx-00** [comment]
Thank you~

**Comment by Neo-xbx-00** [comment]
No other issues, hh
